[package]
name = "scanmem-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
clap-num = "1.1.1"
rand = "0.8.5"
rand_pcg = "0.3.1"
rustyline = "14.0.0"

[[bin]]
name = "synthetic_load"

[[bin]]
name = "benchmark"