[package]
name = "scanmem-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
clap-num = "1.1.1"
nix = { version = "0.29.0", features = ["signal"] }
rand = "0.8.5"
rand_pcg = "0.3.1"
regex = "1.11.1"
rustyline = "14.0.0"

[lib]
name = "framework"
path = "src/framework/lib.rs"

[[bin]]
name = "synthetic_load"

[[bin]]
name = "benchmark"

[[bin]]
name = "conformance"
